version: '3.8'

services:
  db_microservice:
    build: ./db_microservice
    ports:
      - "8001:8001"
    volumes:
      - ./db_microservice:/app
    environment:
      - DATABASE_URL=sqlite:///./workouts.db

  backend_microservice:
    build: ./backend_microservice
    ports:
      - "8000:8000"
    depends_on:
      - db_microservice
    environment:
      - DB_HOST=db_microservice
    command: ["sh", "-c", "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"]

  frontend_microservice:
    build: ./frontend_microservice
    ports:
      - "8501:8501"
    depends_on:
      - backend_microservice
