version: '3.8'

services:
  db_service:
    build:
      context: ./db_microservice
    ports:
      - "5001:5001"
    container_name: db_service
    restart: always

  backend_service:
    build:
      context: ./backend_microservice
    ports:
      - "5000:5000"
    container_name: backend_service
    restart: always
    depends_on:
      - db_service
    environment:
      - DB_SERVICE_URL=http://db_service:5001
